### ISSUE TITLE
[TASK][client][Create] feature/신고 게시글 작성하기 구현

### ISSUE THREAD

**Issue by zeromountain** [codestates/petguru-client#20]
# ISSUE
- Group: client
- Type: feature
- Detail: 신고 게시글 작성하기 구현

# TODO
- [ ] 신고 게시글 작성하기를 구현합니다.
- [ ] 로그인 여부 확인
- [ ] 반려 동물 정보 입력 || 마이페이지에서 반려동물 정보 가져오기
- [ ] 멀티미디어 파일 업로드

# Estimated time
> 4h

# Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
