### ISSUE TITLE
[TASK][client] pages/랜딩페이지 구현

### ISSUE THREAD

**Issue by zeromountain** [codestates/petguru-client#3]
# ISSUE
- Group: client
- Type: feature
- Detail: 서비스를 설명할 수 있는 페이지

# TODO
- [ ] 페이지에 커버 이미지 담기
- [ ] 카피 문구 삽입
- [ ] 랜딩페이지 디자인 작업

# Estimated time
> Pick one
`6h`

# Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
