### ISSUE TITLE
[TASK][client] pages/메인페이지 구현

### ISSUE THREAD

**Issue by zeromountain** [codestates/petguru-client#9]
# ISSUE
- Group: client
- Type: pages, feature
- Detail: 메인페이지 구현

# TODO
- [ ] 질문 게시글 추천 순으로 보여주기
- [ ] 실종 게시글 최신 순으로 보여주기
- [ ] 일반 배너 넣기
- [ ] 롤링배너 넣기(Advanced)

# Estimated time
> 4h

# Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
